/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ArmsAPI: typeof import('./src/api/hotta/arms')['ArmsAPI']
  const AuthAPI: typeof import('./src/api/auth')['AuthAPI']
  const AuthUtils: typeof import('./src/utils/auth')['AuthUtils']
  const BlogAPI: typeof import('./src/api/other/blog')['BlogAPI']
  const EventNewsAPI: typeof import('./src/api/hotta/event-news')['EventNewsAPI']
  const FoodAPI: typeof import('./src/api/hotta/food')['FoodAPI']
  const MimicryAPI: typeof import('./src/api/hotta/mimicry')['MimicryAPI']
  const UploadAPI: typeof import('./src/api/upload')['UploadAPI']
  const WillpowerAPI: typeof import('./src/api/hotta/willpower')['WillpowerAPI']
  const generateKey: typeof import('./src/utils/index')['generateKey']
  const httpRequest: typeof import('./src/api/axios')['httpRequest']
  const isEmpty: typeof import('./src/utils/index')['isEmpty']
  const mix: typeof import('./src/utils/index')['mix']
  const request: typeof import('./src/utils/request')['default']
  const setProperty: typeof import('./src/utils/index')['setProperty']
  const usePermissStore: typeof import('./src/store/permiss')['usePermissStore']
  const useSidebarStore: typeof import('./src/store/sidebar')['useSidebarStore']
  const useTabsStore: typeof import('./src/store/tabs')['useTabsStore']
  const useThemeStore: typeof import('./src/store/theme')['useThemeStore']
  const useUserStore: typeof import('./src/store/user')['useUserStore']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { AuthAPI, AuthAPI } from './src/api/auth'
  import('./src/api/auth')
  // @ts-ignore
  export type { ArmsAPI } from './src/api/hotta/arms'
  import('./src/api/hotta/arms')
  // @ts-ignore
  export type { EventNewsAPI } from './src/api/hotta/event-news'
  import('./src/api/hotta/event-news')
  // @ts-ignore
  export type { FoodAPI } from './src/api/hotta/food'
  import('./src/api/hotta/food')
  // @ts-ignore
  export type { MimicryAPI } from './src/api/hotta/mimicry'
  import('./src/api/hotta/mimicry')
  // @ts-ignore
  export type { WillpowerAPI } from './src/api/hotta/willpower'
  import('./src/api/hotta/willpower')
  // @ts-ignore
  export type { UploadAPI, UploadAPI } from './src/api/upload'
  import('./src/api/upload')
  // @ts-ignore
  export type { BlogAPI } from './src/api/other/blog'
  import('./src/api/other/blog')
  // @ts-ignore
  export type { AuthUtils } from './src/utils/auth'
  import('./src/utils/auth')
}
