// Generated by 'unplugin-auto-import'
export {}
declare global {
  const ArmsAPI: typeof import('./src/api/hotta/arms')['ArmsAPI']
  const AuthAPI: typeof import('./src/api/auth')['AuthAPI']
  const AuthUtils: typeof import('./src/utils/auth')['AuthUtils']
  const UploadAPI: typeof import('./src/api/upload')['UploadAPI']
  const WillpowerAPI: typeof import('./src/api/hotta/willpower')['WillpowerAPI']
  const china: typeof import('./src/utils/china')['default']
  const fetchData: typeof import('./src/api/index')['fetchData']
  const fetchRoleData: typeof import('./src/api/index')['fetchRoleData']
  const fetchUserData: typeof import('./src/api/index')['fetchUserData']
  const httpRequest: typeof import('./src/api/axios')['httpRequest']
  const isEmpty: typeof import('./src/utils/index')['isEmpty']
  const mix: typeof import('./src/utils/index')['mix']
  const request: typeof import('./src/utils/request')['default']
  const setProperty: typeof import('./src/utils/index')['setProperty']
  const usePermissStore: typeof import('./src/store/permiss')['usePermissStore']
  const useSidebarStore: typeof import('./src/store/sidebar')['useSidebarStore']
  const useTabsStore: typeof import('./src/store/tabs')['useTabsStore']
  const useThemeStore: typeof import('./src/store/theme')['useThemeStore']
  const useUserStore: typeof import('./src/store/user')['useUserStore']
}
